name: mathtools
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  currency_converter: ^2.0.0
  currency_converter_pro: ^0.0.7
  file_picker: ^10.1.9
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.3
  flutter_math_fork: ^0.7.3
  flutter_plot: ^0.1.0
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  heroicons: ^0.11.0
  http: ^1.4.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  imgbb: ^0.0.1-beta
  lottie: ^3.3.1
  math_expressions: ^2.7.0
  provider: ^6.1.5
  scidart: ^0.0.2-dev.12
  shared_preferences: ^2.5.3
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon.png"

flutter:
  assets:
    - assets/icon.svg
    - assets/icon.png
    - assets/math_pattern.png    
    - assets/animations/success.json
    - assets/images/default_avatar.png
  uses-material-design: true