// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKVjFEvS3GyXY_yoU5SQnMb6F7ZQoF5XM',
    appId: '1:315973252554:web:33ca53eacc6984b71acb33',
    messagingSenderId: '315973252554',
    projectId: 'mathtools-3f671',
    authDomain: 'mathtools-3f671.firebaseapp.com',
    storageBucket: 'mathtools-3f671.firebasestorage.app',
    measurementId: 'G-1R73851TCR',
    databaseURL: 'https://mathtools-3f671-default-rtdb.firebaseio.com',    
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV34tIBGfAVmyz3JvzCB6O-EYvFQhCo-4',
    appId: '1:315973252554:android:6d3a1c769d6329591acb33',
    messagingSenderId: '315973252554',
    projectId: 'mathtools-3f671',
    storageBucket: 'mathtools-3f671.firebasestorage.app',
    databaseURL: 'https://mathtools-3f671-default-rtdb.firebaseio.com',    
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArBSWbrGk0GM7Je4NYrRLSj-rg6V8BRhM',
    appId: '1:315973252554:ios:d0a80242da184f181acb33',
    messagingSenderId: '315973252554',
    projectId: 'mathtools-3f671',
    storageBucket: 'mathtools-3f671.firebasestorage.app',
    iosBundleId: 'me.nazajf.mathtools',
    databaseURL: 'https://mathtools-3f671-default-rtdb.firebaseio.com',    
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArBSWbrGk0GM7Je4NYrRLSj-rg6V8BRhM',
    appId: '1:315973252554:ios:d0a80242da184f181acb33',
    messagingSenderId: '315973252554',
    projectId: 'mathtools-3f671',
    storageBucket: 'mathtools-3f671.firebasestorage.app',
    iosBundleId: 'me.nazajf.mathtools',
    databaseURL: 'https://mathtools-3f671-default-rtdb.firebaseio.com',    
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKVjFEvS3GyXY_yoU5SQnMb6F7ZQoF5XM',
    appId: '1:315973252554:web:9a9a8e2b49c385151acb33',
    messagingSenderId: '315973252554',
    projectId: 'mathtools-3f671',
    authDomain: 'mathtools-3f671.firebaseapp.com',
    storageBucket: 'mathtools-3f671.firebasestorage.app',
    measurementId: 'G-M5PEJE56ED',
    databaseURL: 'https://mathtools-3f671-default-rtdb.firebaseio.com',    
  );
}
